---
name: YOLOv9 Builder
version: "1.0.8"
slug: yolov9_builder
description: >
  Eksportuje model YOLOv9 do formatu ONNX i zapisuje do /share/yolov9/
  dla Frigate NVR. Wybierz rozmiar modelu i wariant, uruchom raz.
url: https://github.com/dziobson/elFrigate
arch:
  - amd64
  - aarch64
init: false
map:
  - share:rw
startup: once
options:
  model_size: "c"
  image_size: 640
schema:
  model_size: "list(t|s|c|m|e)"
  image_size: "list(320|416|640|1280)"
