---
name: YOLOv9 Builder (640×640)
version: "1.0.4"
slug: yolov9_builder
description: >
  Jednorazowe narzędzie do kopiowania modelu YOLOv9-c 640×640 (ONNX)
  do /share/yolov9/ dla Frigate NVR (elFrigate). Uruchom raz i zatrzymaj.
url: https://github.com/dziobson/elFrigate
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
startup: once
options: {}
schema: {}
